# Generated by Django 5.1.7 on 2025-04-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
