# Generated by Django 5.1.7 on 2025-04-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pollss', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('children', models.IntegerField()),
                ('home_owner', models.BooleanField(default=False)),
                ('cars', models.IntegerField()),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(choices=[('Clerical', 'Clerical'), ('Management', 'Management'), ('Manual', 'Manual'), ('Professional', 'Professional'), ('Skilled Manual', 'Skilled Manual')], max_length=50)),
                ('education', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Graduate Degree', 'Graduate Degree'), ('High School', 'High School'), ('Partial College', 'Partial College'), ('Partial High School', 'Partial High School')], max_length=50)),
                ('marital_status', models.BooleanField(default=False)),
                ('gender', models.BooleanField()),
                ('commute_lower', models.FloatField()),
                ('commute_upper', models.FloatField()),
                ('region', models.CharField(choices=[('Europe', 'Europe'), ('North America', 'North America'), ('Pacific', 'Pacific')], max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
