# Generated by Django 5.1.7 on 2025-04-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictioninput',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
