# Generated by Django 5.1.7 on 2025-04-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0004_alter_predictioninput_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictioninput',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
