# Generated by Django 5.1.5 on 2025-04-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0005_alter_predictioninput_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='titanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pclass', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
                ('sibsq', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('embC', models.IntegerField()),
                ('embQ', models.IntegerField()),
                ('embS', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PredictionInput',
        ),
    ]
